### ISSUE TITLE
[BUG] PM status is active for SDW master with non-existence SDW device

### ISSUE THREAD

**Issue by RanderWang** [thesofproject/linux#1361]
On Comet-lake with 3 SDW codecs, rt715 on link0, rt1308 on link1, rt715 on link3 and no device on link2. After rebooting, SDW2 master on link2 is always active, and this makes SOF always active.

The expect behavior is if there is one link without any devices, their pm_runtime status should be marked as ‘Unsupported’, and that should not prevent the system from going to sleep nor should it have any impact on other devices

**Comment by RanderWang** [comment]
@plbossart I checked the device. there are two device nodes under SDW master-2. Their pm status are Unsupported. But for master-2, the pm status is active. to make master-2 to sleep, we need to call pm_request_idle(https://github.com/RanderWang/linux/commit/42eb0aaeb09cc6733cb0ac44448137634c4aa593). Although we invoke many PM functions at https://github.com/RanderWang/linux/blob/42eb0aaeb09cc6733cb0ac44448137634c4aa593/drivers/soundwire/intel.c#L1339, PM will not schedule a work to trigger sleep until pm_request_idle or pm_put_xxx are invoked. For other master-0, 1, 3, pm_put_xxx will be invoked when setting registers for codec

**Comment by plbossart** [comment]
ok, this may be a configuration we didn't test.
Are you saying there are 4 links active? or is link2 marked as hw_disabled? what happens if you force the hw_disabled flag (with a quirk)?

I am not sure if calling pm_runtime_idle() is a generic solution. If for some reason a codec only reports on the bus say 20s after boot, then the master will already be in suspended mode.

This may be an optional case we need to deal with (e.g. with a quirk).

**Comment by plbossart** [comment]
@RanderWang check #1368, I took your idea but made it conditional
