### ISSUE TITLE
[BUG][CML]Observe sound setting list update when switching output sources with WD19 dock connected

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1419]
**Describe the bug**
Observe sound setting list update when select HDMI from speaker source when both DP and HDMI are connected

**To Reproduce**
1. WD19 Dock is connected
2. Switch audio output sources in sound setting
![image](https://user-images.githubusercontent.com/49641224/68000759-41c46b00-fc9c-11e9-84c0-aacf31ee8a1f.png)

[VID_20191101_110904.zip](https://github.com/thesofproject/linux/files/3796582/VID_20191101_110904.zip)

**Reproduce Rate**
90%

**Actual result**
Observe the highlight will flash on the specified output device. Please see the video.

**Expected result**
Should switch smoothly

Error seen with firmware master and kernel integration/soundwire-latest branch.
**Environment**
Kernel repo	https://github.com/thesofproject/linux/commits/release/sof-v5.0 (8ea23bd)
Firmware repo	https://github.com/thesofproject/sof/tree/cml-hda-dmic-001-drop-stable (6cc8da10)
Topology: 	Same as above SOF repo, sof-hda-generic.tplg
UCM	https://github.com/juimonen/alsa-ucm-conf-1/tree/dell_test (3333df89 sof-skl_hda: add priorities to use cases )
Kconfig:	https://github.com/thesofproject/kconfig(3d5d665) + PR#15

Logs are disabled.

**Comment by ClarexZhou** [comment]
Similar with #1400

**Comment by kv2019i** [comment]
Rootcause seems to be that PA does one extra hop before switching to target output and this is sometimes shown in the UI, causing the flicker in the GUI list. I'll mark this as P3 as audio functionality is not impacted.

**Comment by kv2019i** [comment]
To add some details, here's what happens in Pulseaudio (move to HDMI1 to HDMI2):

1. output change is initiated
Nov  1 22:39:43 u-Latitude-3311 pulseaudio[8434]: [pulseaudio] protocol-native.c: Application "GNOME Volume Control Dialog" requests card profile change. card 
= alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic, profile = Hdmi2

2. as part of the profile change the old HDMI1 sink is disabled, this causes the sink to be briefly routed to USB audio (due to priorities)
Nov  1 22:39:43 u-Latitude-3311 pulseaudio[8434]: [pulseaudio] core.c: default_sink: alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.Hdmi1__hw_sofskl
hdacard_3__sink -> alsa_output.usb-Generic_USB_Audio_200901010001-00.HiFi__hw_Dock_1__sink

3. once HDMI2 is set up, stream is moved to final destination
Nov  1 22:39:43 u-Latitude-3311 pulseaudio[8434]: [pulseaudio] core.c: default_sink: alsa_output.usb-Generic_USB_Audio_200901010001-00.HiFi__hw_Dock_1__sink -> alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.Hdmi2__hw_sofsklhdacard_4__sink

As audio is routed briefly to another sink, this shows as flicker in the UI list that monitors PA events.

This seems to be a feature of Pulseaudio, so I propose to close this. Ok @ClarexZhou  , @mengdonglin 
and @juimonen ?

**Comment by ClarexZhou** [comment]
close for seems Pulseaudio feature and reported with ucm1
