### ISSUE TITLE
[Bug]Mic mute LED still light for DMIC after selecting headset mic as input source.

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1621]
**Describe the bug**
If DMIC and headset MIC mute status is different. Mic mute LED still light for DMIC after selecting headset mic as input source. 

More info:
Dmic LED works according to “Dmic0 Capture Switch”
Headset MIC works according to ‘Capture Switch’

**To Reproduce**
1.	Both Headset mic and DMIC are unmuted
2.	Select DMIC as input source, press MIC mute button to mute-<MIC mute LED light on successfully.
3.	Select Headset MIC as input source ->Headset MIC is keeps unmuted ->check Mic mute LED->Failed. MIC mute LED keeps light on 

**Reproduce Rate**
100%

**Actual result**
MIC mute LED keeps light on 

**Expected result**
MIC mute LED switch to indicate current used headset Mic status, light off.

**Environment**
Kernel: release/sof-v5.0 32c6c62
Firmware: https://github.com/thesofproject/linux-firmware/tree/master/intel/sof/cnl/intel  sof-cnl-v1.3-0f73628.ri rename to sof-cnl.ri   
Kernel config: Run https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh
Topology: Same with FW branch, cml-hda-dmic-002-drop-stable,  sof-hda-generic-2ch.tplg
platform: Lenovo WHL Laptop with codec ALC285 in HDA mode
UCM: https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/, commit id 53f931681

**Comment by libinyang** [comment]
Hi Jaska, if you don't have time to debug this issue, I can help to debug on it after I get the Lenovo laptop. I think debugging this issue can help me to understand how LED is working in pulseaudio better.

**Comment by juimonen** [comment]
@libinyang yes thanks, very much appreciated!

**Comment by juimonen** [comment]
@ClarexZhou this is not sof firmware /sof kernel driver issue. Problem is that we are toggling 1 resource (mute led) from 2 different paths and pulseaudio and alsa have both "redundancy" checking for existing mute values.

1) Ubuntu sound UI tries to set proper mute value when changing the source (dmic vs. headset mic). 
When you mute dmic, we get event to kernel. Now when we switch to headsetmic in UI, the UI sets unmute,but pulseaudio notices that it is already unmuted -> no point of setting the unmute -> no message to kernel -> mute led is not turned off (even though the mic is unmuted)
2) If I remove the redundancy check from Pulseaudio, we have same behavior. This is because alsa does exactly similar redundancy check, thus we never get the mute/unmute setting to kcontrol/sof driver -> mute led stays on previous value

I will ask both pulseaudio and alsa folks can we do something to this, as I don't think it is a problem of blocking the same consecutive values. I think it is very marginal case that someone tries to bomb pulseaudio/alsa with same value...

**Comment by ClarexZhou** [comment]
Wait for fix by future global mute solution
