### ISSUE TITLE
[BUG]DMIC muted status will change to unmuted status after unplug headset.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1824]
**Describe the bug**
DMIC mute status will change to unmute after unplug headset, and Mute LED will off.

**To Reproduce** 
Step1:  No headset connection, DMIC is unmuted
Step2:  Plug in headset-> select DMIC in input source-> Mute DMIC
Step3: unplug headset ->DMIC is unmuted. LED also off
Step4: plugin headset again->DMIC is muted, LED also on. 

**Reproduced rate**
100%
 
**Expected result**
DMIC should be always in muted status. 

**Actual result**
DMIC will change to unmute status after unplug headset.

**Environment**
kernel: https://github.com/bardliao/linux/tree/sdw_release commit: 38d0dcd5
FW: https://github.com/thesofproject/sof/commits/cml-010-drop-stable commit: 5e5f69e + PR#2431
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg rename to sof-cml-rt711-rt1308-rt715.tplg 
platform: CML Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

**Comment by ClarexZhou** [comment]
Error also seen on WHL laptop when plug HDMI with UCM https://github.com/thesofproject/alsa-ucm-conf/tree/sof_ucm1/ucm/LENOVO-20QE000VMC-ThinkPadX1Carbon7th-20QE000VMC and sof-v5.0 kernel+ cml-hda-dmic-002-drop-stable firmware.

**Comment by ClarexZhou** [comment]
Error not seen after Disable “
load-module module-device-restore
load-module module-stream-restore
  load-module module-card-restore”
in /etc/pulse/default.pa. 

But will also have below 2 issues once disable above function:
1.  Parecord used source will not change if select DMIC/ headset MIC from Sound input setting
2.  Mic will always auto unmuted after system reboot.

@libinyang @juimonen Could you please comment on this?

**Comment by juimonen** [comment]
@ClarexZhou I think this is the same thing as the mute led issues you've filed before... So we have 2 mic mutes behind 1 led. Currently sound-settings UI doesn't handle this very well (it kind of assumes individual leds for all sources. 

I think in the end we should change the UI so that it remembers the mute and it is muting for all sources or unmute for all sources. Otherwise it is very difficult to make it logical for the user with 1 led and several sources. And when the source changes UI/Pulseaudio should call mute/unmute always for that source.

**Comment by mengdonglin** [comment]
Same cause as #1621

**Comment by ClarexZhou** [comment]
Wait for fix by future global mute solution
