### ISSUE TITLE
[BUG][UCM2][CML]Output device will auto switch to HDMI/DP when switch output devices between headphone and speaker.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2101]
**Describe the bug**
When HDMI/DP is connected to right port of Stradale, switch output source between headphone and speaker, the output source will auto switch to HDMI/DP. But When HDMI/DP is connected to left port of Stradale, error cannot be seen.

Precondition:
1.Install ubuntu 20.04
2.Upgrade pulseaudio (https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：36a4923f)+https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290)
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/40

**To Reproduce**
1.Boot up system with HDMI/DP connected.
2.Open sound setting.
3.Switch source between headphone and speaker in output device.
(https://github.com/thesofproject/sof-test/blob/master/test-case/manual/check-pulseaudio.md)

**Reproduce rate**
5/5

**Expected result**
Can switch normally between headphone and speaker in output device.

**Actual result**
Output device will auto switch to HDMI/DP when switch output devices between headphone and speaker.

![Screenshot from 2020-05-13 13-38-07](https://user-images.githubusercontent.com/56706782/81775353-49a07a00-951f-11ea-978a-1f85d9ed804c.png)

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:0773fe
FW: https://github.com/thesofproject/sof/commits/master commit: 782066
Tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

**Comment by mengdonglin** [comment]
This UCM+ PulseAudio test combination is deprecated now.
Because @plbossart @perexg NAKed defining Conflicting Device in UCM if these PCM devices are not conflicting in hardware. So we can no longer define such fake Conflicting Device in single-profile UCM, and depend on PulseAudio to automatically create profiles per conflicting device group for
for the exclusive device usage: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290

Please find more info in thesofproject/alsa-ucm-conf#40 (comment)

**Comment by ClarexZhou** [comment]
Close first since pulseaudio create profiles PR https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290 might not be used.
