### ISSUE TITLE
[BUG][UCM2][CML]Sound setting shows empty selection after reboot with HDMI/DP highlight in output device. 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2102]
**Describe the bug**
Select HDMI/DP as output source in sound setting, then reboot. Sound setting will have empty selection. Click the empty selection, then output source will show up.

Precondition:
1.Install ubuntu 20.04
2.Upgrade pulseaudio (https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：36a4923f)+https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290)
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/40

**To Reproduce**
1.Select HDMI/DP as output device in sound setting
2.Reboot system.
3.Open sound setting .

**Reproduce rate**
5/5

**Expected result**
Output device should show HDMI/DP source.

**Actual result**
Output/input device shows empty selection. Then click it and all source selection will show up.

![IMG_20200513_143720](https://user-images.githubusercontent.com/50347470/81779613-9ee08980-9527-11ea-8a61-aab870a50d8b.jpg)

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:0773fe
FW: https://github.com/thesofproject/sof/commits/master commit: 782066
Tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-U Laptop with codec ALC711,  RT1308, RT715 in SDW mode.

**Comment by mengdonglin** [comment]
This UCM+ PulseAudio test combination is deprecated now.
Because @plbossart @perexg NAKed defining Conflicting Device in UCM if these PCM devices are not conflicting in hardware. So we can no longer define such fake Conflicting Device in single-profile UCM, and depend on PulseAudio to automatically create profiles per conflicting device group for
for the exclusive device usage: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290

Please find more info in thesofproject/alsa-ucm-conf#40 (comment)

**Comment by ClarexZhou** [comment]
Close first since pulseaudio create profiles PR https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290 might not be used.
