### ISSUE TITLE
[BUG][UCM2][SDW]Output device can't auto highlight to HDMI/DP after connecting HDMI/DP with right port.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2105]
**Describe the bug**
Output device can't auto highlight to HDMI/DP after connecting HDMI/DP with right port of CML-H 
laptop. 
Note:Error not seen with left port of CML-H. 
[amixer contents.txt](https://github.com/thesofproject/linux/files/4620875/amixer.contents.txt)

Precondition:
1.Install ubuntu 20.04
2.Upgrade pulseaudio (https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：36a4923f)+https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290)
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/40

**To Reproduce**
1.Boot up system.
2.Open sound setting
2.Plug in HDMI/DP (https://github.com/thesofproject/sof-test/blob/master/test-case/manual/check-pulseaudio.md)

![Screenshot from 2020-05-13 17-02-29](https://user-images.githubusercontent.com/56706782/81793424-ee30b500-953b-11ea-97dc-ea6a3152ff0e.png)

**Reproduce rate**
5/5

**Expected result**
Output device should auto highlight to HDMI/DP after connecting HDMI/DP with right port of CML-H laptop. 

**Actual result**
Output device can't auto highlight to HDMI/DP after connecting HDMI/DP with right port of CML-H 
laptop. 

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:0773fe
FW: https://github.com/thesofproject/sof/commits/master commit: 782066
Tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

**Comment by mengdonglin** [comment]
This UCM+ PulseAudio test combination is deprecated now.
Because @plbossart @perexg NAKed defining Conflicting Device in UCM if these PCM devices are not conflicting in hardware. So we can no longer define such fake Conflicting Device in single-profile UCM, and depend on PulseAudio to automatically create profiles per conflicting device group for
for the exclusive device usage: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290

Please find more info in thesofproject/alsa-ucm-conf#40 (comment)

**Comment by ClarexZhou** [comment]
Close first since pulseaudio create profiles PR https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290 might not be used.
