### ISSUE TITLE
[UCM2][BUG][CML]Only one HDMI/DP has sound output when two HDMI/DP are connected.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2106]
**Describe the bug**
With two HDMI/DP connected, output device switch to HDMI A, S/PDIF of HDMI A can auto unmute while HDMI B cannot.
[amixer contents.txt](https://github.com/thesofproject/linux/files/4620875/amixer.contents.txt)

Precondition:
1.Install ubuntu 20.04
2.Upgrade pulseaudio (https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：36a4923f)+https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290)
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/40

**To Reproduce**
1.Boot up system with two HDMI/DP connected;
2.Open sound setting;
3.Run "paplay wav/48California_Dreaming.wav -vvv" and check the sound output
4.Switch source and check the status of  S/PDIF , S/PDIF 1 and S/PDIF 2 (https://github.com/thesofproject/sof-test/blob/master/test-case/manual/check-pulseaudio.md)

<img width="440" alt="22" src="https://user-images.githubusercontent.com/56706782/81802608-fba06c00-9548-11ea-928b-11b88e24831e.PNG">

**Reproduce rate**
5/5

**Expected result**
 All HDMI/DP should have sound output when connected with device.

**Actual result**
Only one HDMI/DP has sound output when two HDMI/DP connected.

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:0773fe
FW: https://github.com/thesofproject/sof/commits/master commit: 782066
Tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

**Comment by mengdonglin** [comment]
This UCM+ PulseAudio test combination is deprecated now.
Because @plbossart @perexg NAKed defining Conflicting Device in UCM if these PCM devices are not conflicting in hardware. So we can no longer define such **fake** Conflicting Device in single-profile UCM, and depend on PulseAudio to automatically create profiles per conflicting device group for 
for the exclusive device usage: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290

Please find more info in https://github.com/thesofproject/alsa-ucm-conf/pull/40#discussion_r424489241

**Comment by ClarexZhou** [comment]
Close first since pulseaudio create profiles PR https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/290 might not be used.
