### ISSUE TITLE
[BUG][TGL] pop noise issue on max98357 speaker when doing pause/resume test

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#2111]
**Describe the bug**
We tried rt5682+max98357 codec(I2S mode) on TGL Chromebook, but found that when resuming the playback on speaker, we can hear the pop noise clearly and sometimes the playback speed will become very slow but this issue cannot be reproduced with max98373 codec. Since this max98357 is non smart amplifier codec. so not sure if this is codec specific.

**To Reproduce**
1. $ aplay -Dhw:0,0 -f s16_le -c 2 -r 48000 audio.wav -i
2. press space key repeatedly to pause/resume playback.

**Reproduction Rate**
8/10

**Expected behavior**
no pop noise after resuming playback

**Impact**
pop noise

**Environment**

1.	FW: https://github.com/thesofproject/sof/tree/tgl-006-drop-stable
2.	Kernel: tip of sof-dev, commit 0773fe68(kernel Debian is attached).
Revert regression on USB-C 6a7c533d4a1854f54901a065d8c672e890400d8a
Revert regression on PINCTRL cd0a32371db73d0b50536a7ca4f036abddff0d1d
3.	Kconfig:
tip of https://github.com/thesofproject/kconfig commit 6555fb9d9 
4.	Topology: tgl-006-drop-stable          
Sof-tgl-max98357a-rt5682.tplg   

**dmesg and trace **
[dmesg.txt](https://github.com/thesofproject/linux/files/4626744/dmesg.txt)
[logger.txt](https://github.com/thesofproject/linux/files/4626749/logger.txt)

**Comment by keqiaozhang** [comment]
@naveen-manohar , please help to check this issue to see if this is max98357 codec restriction. Thanks.

**Comment by plbossart** [comment]
@keqiaozhang is this still relevant now?

**Comment by YvonneYang2** [comment]
Issue cannot be reproduced with test recipe as below:

Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev commit:0d22f66b7
Revert regression on USB-C 6a7c533d4a1854f54901a065d8c672e890400d8a
Revert regression on PINCTRL cd0a32371db73d0b50536a7ca4f036abddff0d1d
FW: https://github.com/thesofproject/sof/tree/tgl-006-drop-stable plus https://github.com/thesofproject/sof/pull/2987
TPLG: same as fw sof-tgl-max98357a-rt5682.tplg

**Comment by plbossart** [comment]
no information provided, closing.

**Comment by ClarexZhou** [comment]
Error still seen on max98357 speaker and max98373 speaker. 
Error can be observed when pause/resume during playing sine wave. Reopen
![image](https://user-images.githubusercontent.com/49641224/86434330-cb4aa200-bd2f-11ea-92d4-f0d318b3c351.png)
[captureaudio-wav.zip](https://github.com/thesofproject/linux/files/4867872/captureaudio-wav.zip)


FW: on https://github.com/thesofproject/sof/tree/tgl-007-drop-stable.
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)
+ PR#2208 + PR#2240 for DP fix 
+ PR#2184 for wov S0i2 
+PR#2238 for max98373-sdw jack switch

**Comment by ClarexZhou** [comment]
Error also occurred when start and stop aplay.

**Comment by naveen-manohar** [comment]
@sathya-nujella can you please help check this ? I dont have the daughter card with i2s-max98357 or i2s-max98373 codec.
And with sdw-max98373 daughtercard, I'm not observing the pop-noise. 

@ClarexZhou : Can you please confirm if issue reproduced on max98373 speaker codec is of i2s or sdw based ?

**Comment by naveen-manohar** [comment]
verified on **sdw**-rt5682-max98373 and i'm not observing pop noise during speaker aplay(pause-resume)

**Comment by ClarexZhou** [comment]
Can observe slight pop when playing sine wave on i2s-rt5682-max98373
And here attached the captured audio via DSM.
![image](https://user-images.githubusercontent.com/49641224/86737198-ad9a7700-c066-11ea-9b68-40978ddfe416.png)


Also can observe slight pop when playing sine wave on sdw-rt5682-max98373. But seen no this pop on captured audio via DSM. 
![image](https://user-images.githubusercontent.com/49641224/86736809-64e2be00-c066-11ea-971b-1b1281bb8f29.png)
[i2s_sdw_capture.zip](https://github.com/thesofproject/linux/files/4883242/i2s_sdw_capture.zip)

**Comment by naveen-manohar** [comment]
@ClarexZhou: Good Info. & Observation. 
I tried the same method for DSM on SDW and it appears clean.

![image](https://user-images.githubusercontent.com/33264352/86771578-1df9c600-c070-11ea-9121-95ba1f93b581.png)
[echo_play-pause.zip](https://github.com/thesofproject/linux/files/4884407/echo_play-pause.zip)

**Comment by plbossart** [comment]
For TGL, we have SDW support for max98373. The bug report mentions I2S w/ max98357. Are we talking about the same codec?

**Comment by ClarexZhou** [comment]
split https://github.com/thesofproject/linux/issues/2255 to track issue for I2S max98373.

**Comment by Liviali155** [comment]
On TGL chromebook with codec 98357 in I2S mode reproduced the issue of   pop noise and playback speed become very slow
1."sudo reboot" to reboot sysytem
2.open terminal1 to run "aplay -Dhw:0,0 -r48000 -c2 -fs24_le wav/48California_Dreaming.wav -vv -i"
3 .open terminal2 to run " arecord -Dhw:0,99 -r48000 -c4 -fs32_le s30.wav -vv -i"
4.do pause/release slowly of arecord(0,99) about 20 times
5.do pause/release slowly of aplay(0,0)about 5 times (need to pause/release slowly,otherwise will reproduce issue https://github.com/thesofproject/sof/issues/2749)

Pop noise occured when pause/release aplay(0,0),Aplay of speaker(0,0) will  become very slow

[sof-logger_slow.log](https://github.com/thesofproject/linux/files/4889508/sof-logger_slow.log)
[dmesg_slow.log](https://github.com/thesofproject/linux/files/4889507/dmesg_slow.log)


Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
Kernel: Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev (commit: 1b2f260)

PR#2208 for DP fix
PR#2184 for wov S0i2
+PR#2238 for max98373-sdw jack switch
codec hack commit to verify this captured data.
revert regression on USB-C 6a7c533 for volteer
revert d4b41f8bb
revert regression on PINCTRL cd0a323 for volteer
https://github.com/thesofproject/sof/commits/releases/tgl/v7.0-rc7 ,commit: 33cfa90e

**Comment by RanderWang** [comment]
let's track https://github.com/thesofproject/linux/issues/2255
