### ISSUE TITLE
[BUG][UCM2][CML]HDMI/DP will not have sound output after plug in another DP/HDMI. 

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2114]
**Describe the bug**
HDMI/DP will not have sound output after plug in another DP/HDMI. After issue occured, switch source can recover.

Precondition:
1.Install ubuntu 20.04
2.Pulseaudio version: 13.99.1 
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/41

**To Reproduce**
1. Boot up system with two DP/HDMI displays connected;
2. Open sound setting ->select one HDMI/DP as output device;
3. Run "paplay wav/48California_Dreaming.wav -vvv" ;
4. Unplug one HDMI/DP display and check the sound output is OK on another HDMI/DP display;
5. Plug in the other HDMI/DP display again and check the sound output on this display;

**Reproduce rate**
5/5

**Expected result**
HDMI/DP should have sound output after plug in another DP/HDMI. 

**Actual result**
HDMI/DP will not have sound output after plug in another DP/HDMI. 

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:a43e72a3
FW: https://github.com/thesofproject/sof/commits/master commit: 83cecc95
Tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

**Comment by libinyang** [comment]
with the latest recipe:

UCM2: https://github.com/alsa-project/alsa-ucm-conf(commit: 3e897306)
Alsa-lib: http://sof-ci-storage.sh.intel.com/share/alsa/alsa-lib/latest/libasound2_1.2.3.2-a3ca480/
Pulseaudio: http://sof-ci-storage.sh.intel.com/share/pulseaudio/latest/pulseaudio_13.99.1.1-47d8112/
Gnome: 1:3.36.2-0ubuntu1++testswitch - can download form Canonical:
sudo add-apt-repository ppa:hui.wang/switch-audio
sudo apt-get update
sudo apt install gnome-control-center

This bug is fixed.
tested on HDA and SDW
