### ISSUE TITLE
[BUG][CML][SDW UCM2]Input source will auto switch source from DMIC to headset once change source in output device

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2115]
**Describe the bug**
Input source will auto switch source from DMIC to headset once switch source in output device.

Precondition:
1.Install ubuntu 20.04
2.Pulseaudio version: 13.99.1
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/41

**To Reproduce**
1. Boot up system with headset and HDMI/DP external port connected.
2. Open sound setting, select headphone as output device and DMIC as input device 
3. Switch output device to other source, then switch it to headphone back.
4. Check the input source.

**Reproduce rate**
5/5

**Expected result**
Input device should stay in DMIC when output source is headphone.

**Actual result**
Input device will auto switch to headset after step 3.

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:0a43e72a3
FW: https://github.com/thesofproject/sof/commits/master commit: 83cecc95
Tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
Platform:CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode.

**Comment by libinyang** [comment]
can't reproduce this issue with below recipe:
UCM2: https://github.com/alsa-project/alsa-ucm-conf(commit: 3e897306)
Alsa-lib: http://sof-ci-storage.sh.intel.com/share/alsa/alsa-lib/latest/libasound2_1.2.3.2-a3ca480/
Pulseaudio: http://sof-ci-storage.sh.intel.com/share/pulseaudio/latest/pulseaudio_13.99.1.1-47d8112/
Gnome: 1:3.36.2-0ubuntu1++testswitch - can download form Canonical:
sudo add-apt-repository ppa:hui.wang/switch-audio
sudo apt-get update
sudo apt install gnome-control-center

This bug is fixed.
Verified on SDW
