### ISSUE TITLE
[BUG][CML][UCM2]Output device will not auto switch to headphone after plug in headphone with sound setting open

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2124]
**Describe the bug**
Open sound setting. Wait 10s (wait pulseaudio to suspend), then plug in headphone, the output/input device cannot auto switch to headphone/headset.

Note: If plug in headphone with music paplaying or plug in headphone with sound setting closed, then open sound setting to check it, issue cannot be reproduced.

Precondition:
1.Install ubuntu 20.04
2.Pulseaudio version: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：36a4923f) + https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295 
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/35+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/39

**To Reproduce**
1. Boot up system without any external port connected
2. Open sound setting, then wait 10s
3. Plug in headphone.
4. Check the output/input source.

**Reproduce rate**
5/5

**Expected result**
Output source will auto switch to headphone and input source will auto switch to headset.

**Actual result**
Output source still stays in speaker and input source still stays in DMIC.

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:1697493f
FW: https://github.com/thesofproject/sof/commits/master commit: 83cecc95
Tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
Platform:CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode.

**Comment by ClarexZhou** [comment]
Error not seen with https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295#note_512131, wait Pulseaudio update.

**Comment by libinyang** [comment]
with the latest recipe:

UCM2: https://github.com/alsa-project/alsa-ucm-conf(commit: 3e897306)
Alsa-lib: http://sof-ci-storage.sh.intel.com/share/alsa/alsa-lib/latest/libasound2_1.2.3.2-a3ca480/
Pulseaudio: http://sof-ci-storage.sh.intel.com/share/pulseaudio/latest/pulseaudio_13.99.1.1-47d8112/
Gnome: 1:3.36.2-0ubuntu1++testswitch - can download form Canonical:
sudo add-apt-repository ppa:hui.wang/switch-audio
sudo apt-get update
sudo apt install gnome-control-center

This bug is fixed.
