### ISSUE TITLE
Verbose tracing breaks new logger

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#214]
This is to follow up https://github.com/thesofproject/sof/issues/473 which is closed because this is generic kernel bug on topic/cros-4.14-rebase branch.  We cannot reproduce this issue on topic/sof-dev 

Please more info from https://github.com/thesofproject/sof/issues/473#issuecomment-429867629

**Comment by keyonjie** [comment]
yes, we know this issue with topic/sof-dev, thanks.

**Comment by mengdonglin** [comment]
The related logger issues on cros-4.14-rebase branch includes:
https://github.com/thesofproject/linux/issues/198
https://github.com/thesofproject/sof/issues/401
https://github.com/thesofproject/sof/issues/477

We'd better to verify them as well to make sure logger can work well cros-4.14-rebase

**Comment by Jiangxinx** [comment]
Not reproduced with kernel branch debug/v4.19-backport, on APL UP2 platfrom.

STEP:
1.Enable tracev(trace.h):
-#define TRACEV 0
+#define TRACEV 1
2.re-make sof、soft、logger and replace them on UP2
3.reboot
4.aplay -Dhw:0,0 audio.wav
5.sudo sof-logger -l sof-apl.ldc -t -o logger.log

Test env:
hardware version: UP2
sof-master: 04b1ce48
soft-master: 4ac9248
kernel debug/v4.19-backport: e7da1c44
tplg: sof-apl-pcm512x.tplg

**Comment by keqiaozhang** [comment]
this issue is still there, error message as below:
chronos@localhost ~ $ sudo /usr/local/bin/sof-logger -l /root/sof-apl.ldc-master-11-1 -t
 CORE  LEVEL  COMP_ID        TIMESTAMP            DELTA                FILE_NAME        CONTENT
    0      1  unknown  14605848.125000  14605848.000000          dma-trace.c:417        Number of dropped logs: 0
Error: Invalid number of parameters.
chronos@localhost ~ $ sudo /usr/local/bin/sof-logger -l /root/sof-apl.ldc-master-11-1
 CORE  LEVEL  COMP_ID        TIMESTAMP            DELTA                FILE_NAME        CONTENT
Error: Invalid filename length.

Tested with:
soft-master:4ac9248f
sof-master:43da16
kernel-debug/cros-v4.14-rebase: 90eee4

**Comment by keqiaozhang** [comment]
Sorry, I missed to update the ldc file.
After updated the ldc file, now sof-logger works well without error.
So this issue can be closed now.
