### ISSUE TITLE
[BUG][CML-H][UCM2]Output device will not auto switch to headphone after plug in headphone for the first time.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2148]
**Describe the bug**
Open sound setting. Wait 10s (wait pulseaudio to suspend), then plug in headphone, the output/input device cannot auto switch to headphone/headset. After issue occured unplug then plug in headset can recover. 

Precondition:
1.Install ubuntu 20.04
2.Pulseaudio version: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：3dc525df) + https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295 
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/35+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/39

**To Reproduce**
1) power off  with headphone plugged in
2) unplug headphone
3) power on
4) open sound-setting
5) plugin headphone

**Reproduce rate**
5/5

**Expected result**
Output source will auto switch to headphone and input source will auto switch to headset.

**Actual result**
Output source still stays in speaker and input source still stays in DMIC.

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit: 0d22f66
FW: https://github.com/thesofproject/sof/commits/master commit: 46897802
Tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

**Comment by sinahuang** [comment]
Issue can be fixed by PR https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/302.

**Comment by libinyang** [comment]
This is a bug related the module-default-device-restore
This module will always restore the device which is lastly used. So when it try to restore headphone which is not plugged in, the error happens.

**Comment by libinyang** [comment]
with the latest recipe:

UCM2: https://github.com/alsa-project/alsa-ucm-conf(commit: 3e897306)
Alsa-lib: http://sof-ci-storage.sh.intel.com/share/alsa/alsa-lib/latest/libasound2_1.2.3.2-a3ca480/
Pulseaudio: http://sof-ci-storage.sh.intel.com/share/pulseaudio/latest/pulseaudio_13.99.1.1-47d8112/
Gnome: 1:3.36.2-0ubuntu1++testswitch - can download form Canonical:
sudo add-apt-repository ppa:hui.wang/switch-audio
sudo apt-get update
sudo apt install gnome-control-center

This bug is fixed.
Verified on SDW and sof HDA
