### ISSUE TITLE
[BUG] Very limited sound from Lenovo C940

### ISSUE THREAD

**Issue by Enerccio** [thesofproject/linux#2304]
There are only 2 out of 5 speakers working on Lenovo C940. The issue is being discussed here:

https://bugzilla.kernel.org/show_bug.cgi?id=205755

but I thought maybe you guys could fix it (there are logs and also some startup instructions in the thread) for sof instead, because guy who is working on alsa+linux seems very busy.

**Comment by paulstelian97** [comment]
Might want to also attach the alsa-info.txt file here. You might be having wrong paths somewhere and, if they are, they could be solvable in userspace.

Otherwise, first this needs to be solved for the non-SOF driver, then check if SOF driver still manifests it after the fix.

**Comment by Enerccio** [comment]
http://alsa-project.org/db/?f=c9318eb4757cd27e6af8ea07a509d95140f07f53

Well that is the thing, it looks like no one will solve the non-sof driver. That's why I thought that at least sof driver could fix this issue

**Comment by paulstelian97** [comment]
In general, we could try to find out a solution if it's doable in the userspace. But if the driver itself is in the wrong, we end up not having the required information to update the SOF driver (usually, if it's not Intel hardware specifically, we use code from existing non-SOF drivers as reference on what the hardware wants; but since this problem manifests on the non-SOF driver as well we don't really have a way to fix it -- according to the linked kernel Bugzilla bug there is no documentation that specifies the in-hardware connections so that the software can make them properly).

I'll keep this open in case someone else has an insight. But my personal opinion is to not put your hope into finding a solution with SOF too soon.

**Comment by Enerccio** [comment]
There is some initialization code posted but no response from Kysela so who knows.

**Comment by plbossart** [comment]
SOF only supports 2ch outputs, so the multi-speaker case has to be handled with the codec driver. If you look at the bugzilla information the codec driver needs a set of I2C configurations for the amplifiers.
This is really not an SOF issue proper. I will use our Lenovo contacts to see if they can help.

**Comment by Enerccio** [comment]
I thought this was the code for the amplifiers though: https://bugzilla.kernel.org/show_bug.cgi?id=205755#c33

**Comment by plbossart** [comment]
> I thought this was the code for the amplifiers though: https://bugzilla.kernel.org/show_bug.cgi?id=205755#c33

it's pseudo-code, what's missing is a fixup for this HDaudio codec that will write values in the relevant node to reach those 0x82 and 0x84 I2C config registers

**Comment by plbossart** [comment]
@Enerccio this is really not an SOF issue so I will close this. Lenovo and others are aware of the issue, this isn't a topic our team can do much on.
