### ISSUE TITLE
Keep HD-A support backward compatible with SOF v1.2

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/linux#264]
SOF firmware v1.2 has no support for HD-A links. We need to assure latest kernel (SOF platform driver, machine drivers) can be configured to disable HD-A link support, to work with SOF 1.2 and topology w/o HD-A front & backends.

**Comment by mengdonglin** [comment]
Dependence:

- [ ] https://github.com/thesofproject/linux/pull/257

 - [ ] https://github.com/thesofproject/linux/issues/234

**Comment by plbossart** [comment]
Humm, this is a bit vague. I am all for removing HDA/HDMI support with a config change, but 
1. On what platforms do you want to ensure backwards compatibility? GLK selects HDAC_HDMI in the Kconfig
2. how would you deal with ABI changes that happened since 1.2?
3. how do we provide topologies that have no references to hda/hdmi? it's almost like we'd want two topology files, with HDMI being added in a second step when the kernel has it. I actually like this  idea... Since HDMI is completely independent from the rest it'd be useful to add it conditionally.

**Comment by plbossart** [comment]
no answer in 8 days -> closing.
