### ISSUE TITLE
PGA Master Capture Switch off leaves the right channel go through unmodified.

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2862]
Found during development of https://github.com/thesofproject/linux/pull/2827, somehow we can only get left and right channels with this setting.
````
amixer cset name='PGA2.0 2 Master Capture Switch' 1
````

With this switch off we are still able to capture the right channel, so something is not quite right here. This may be a SoundWire only issue or a more generic one, to be determined.

**Comment by bardliao** [comment]
@plbossart I think the switch value before you set `amixer cset name='PGA2.0 2 Master Capture Switch' 1` was off,on. 
```
test@UP-WHL01:~$ amixer cget name='PGA2.0 2 Master Capture Switch'
numid=24,iface=MIXER,name='PGA2.0 2 Master Capture Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=off,on
```
That's the reason you are able to capture the right channel.
Discussed with @juimonen we think the issue is not seen in a real product is because we set `'PGA2.0 2 Master Capture Switch' 1` in https://github.com/thesofproject/alsa-ucm-conf/blob/master/ucm2/sof-soundwire/rt711.conf

**Comment by plbossart** [comment]
@bardliao I am quite sure it was "off,off". that's why I added this issue. I'll redo the test to confirm.

**Comment by plbossart** [comment]
I need a vacation, the behavior is as expected.
