### ISSUE TITLE
sound does not work on bishop county laptop LAPBC710 / NUC M15

### ISSUE THREAD

**Issue by gigago** [thesofproject/linux#3049]
Hi,

for some time I've been trying to get audio working on a bishop county laptop, distro Arch. Status: no PCM device loaded, maybe some working HDMI devices (couldn't test those yet). I'm looking for expert help now. Some steps taken:

- read up on comparable issues
- upgrade to kernel 5.13
- install sof firmware 1.8
- install alsa ucm
- add module debug parameters
- try different dsp_driver values: auto, legacy, SOF

I also tried remapping _ADRs analogous to the recently added /drivers/soundwire/dmi-quirks, but not with good results. I could not establish the status of the IME on my system but have no reason to assume it's been disabled. Some diagnostic files added:

alsainfo with dsp_driver=1
[alsainfo-k5.13.1-20210713-dsp_driver=1.txt](https://github.com/thesofproject/linux/files/6823801/alsainfo-k5.13.1-20210713-dsp_driver.1.txt)

alsainfo with dsp_driver=3
[alsainfo-k5.13.1-20210713-dsp_driver=3.txt](https://github.com/thesofproject/linux/files/6823803/alsainfo-k5.13.1-20210713-dsp_driver.3.txt)

topologies, DSDT and dmesg excerpt
[sof-topologies_DSDT_dmesg.txt](https://github.com/thesofproject/linux/files/6823825/sof-topologies_DSDT_dmesg.txt)

**Comment by plbossart** [comment]
@gigago I think the problem is that your hardware is based on SoundWire links/codecs but the kernel selects an HDAudio configuration. That cannot possibly work.

It's probably a similar issue to what happened on Ubuntu
[    3.062666] sof-audio-pci-intel-tgl 0000:00:1f.3: No SoundWire machine driver found

I'd bet a beer you don't have this option in your kernel configuration.
CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH=m

That's not going to solve the problem completely, I see that the _ADR is not found so unfortunately we are going to have to add remapping quirks. it's likely the same problem as on HP devices.

But first thing first, please reinstall your kernel with the option above enabled, that should get rid of the HDaudio stuff.

**Comment by plbossart** [comment]
@gigago what is 'bishop county' anyways, the DMI information says it's an Intel platform?

````
Manufacturer:      Intel(R) Client Systems
Product Name:      LAPBC710
Product Version:   M13826-506
Firmware Version:  BCTGL357.0064.2021.0518.1820
System SKU:        BBC710ECB7B02
Board Vendor:      Intel Corporation
Board Name:        LAPBC710
````

**Comment by plbossart** [comment]
I think my theory holds water, in the case of dsp_driver=1 you don't have any external HDaudio codec detected, only Display Audio devices which do use an HDaudio internal link. By using the SoundWire machine driver you should be in a better place.

**Comment by gigago** [comment]
> I'd bet a beer you don't have this option in your kernel configuration.
> CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH=m

I have a special fondness for specialty beers at room temperature, Pierre-Louis. :-) Output of zcat /proc/config.gz | grep SOUNDWIRE

CONFIG_REGMAP_SOUNDWIRE=m
CONFIG_REGMAP_SOUNDWIRE_MBQ=m
CONFIG_SND_INTEL_SOUNDWIRE_ACPI=m
**CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH=m**
CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE_LINK_BASELINE=m
CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE=m
CONFIG_SOUNDWIRE=m
CONFIG_SOUNDWIRE_CADENCE=m
CONFIG_SOUNDWIRE_INTEL=m
CONFIG_SOUNDWIRE_QCOM=m
CONFIG_SOUNDWIRE_GENERIC_ALLOCATION=m

**Comment by gigago** [comment]
> @gigago what is 'bishop county' anyways, the DMI information says it's an Intel platform?
> 
> ```
> Manufacturer:      Intel(R) Client Systems
> Product Name:      LAPBC710
> Product Version:   M13826-506
> Firmware Version:  BCTGL357.0064.2021.0518.1820
> System SKU:        BBC710ECB7B02
> Board Vendor:      Intel Corporation
> Board Name:        LAPBC710
> ```

The Intel naming scheme is rather obscure indeed. AFAICS, the 'Bishop County' moniker can be abbreviated to 'BC', which can be found in the product name. I've seen it used in some of last year's product announcements. The platform is definitely Intel but it may be customized and marketed by OEMs.

**Comment by plbossart** [comment]
ok, so I guess the only problem is that because of the missing _ADR remap we can't find a supported configuration.

Can you try the two patches from https://github.com/thesofproject/linux/pull/3050 to see if that improves the solution.

if it doesn't then add the result of 'grep 25d /sys/bus/acpi/devices/*/adr' and dmesg info with this file added in /etc/modprobe.d/sof-dyndbg.conf 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/6825308/sof-dyndbg.conf.txt)

**Comment by gigago** [comment]
SUCCESS

I patched dmi-quirks and sof_sdw, replacing the apparently undeclared RT711_JD2 with SOF_RT711_JD_SRC_JD2 so it would compile (not sure if this is actually the right driver). TGL LP sound driver has loaded, speaker works.

For completeness sake, here's the post patch alsa-info:
[alsainfo-k5.13.0-20210715-hoera.txt](https://github.com/thesofproject/linux/files/6826182/alsainfo-k5.13.0-20210715-hoera.txt)

More tests to follow to check functionality. So far so good. Thanks a lot for helping out!

**Comment by plbossart** [comment]
Great @gigago, thanks for testing. The JD2 stuff is normal, it's a cleanup we did last week and it's not yet in the mainline. The two definitions are equivalent.

Do you mind removing the option snd_intel_dspcfg: dsp_driver=3, this should be unnecessary now?

The other things to test are
- the jack detection, if this doesn't work with JD2 try JD1. 
- local mic support. that should work out of the box since there is no configuration needed

I'll wait a bit more until I sent those two patches upstream, apparently there are a slew of Intel-designed laptops we didn't even know about, we need to make sure we add the quirks for all of them... Big companies...

**Comment by gigago** [comment]
Mic is registered and appears to be working. Headphone jack does not work, I'll try JD1 later.

Oh, ok. Driver keeps loading correctly without dsp_driver parameter.

**Comment by gigago** [comment]
> I'll wait a bit more until I sent those two patches upstream, apparently there are a slew of Intel-designed laptops we didn't even know about, we need to make sure we add the quirks for all of them... Big companies...

Yes, the present solution is a pain to maintain and makes for some brittle code. Maybe it's possible to test in a more generic way, e.g. for certain combinations of specific hardware addresses and errors?

**Comment by gigago** [comment]
JD1 tested, jack detection works, headphones device (un)registered.

**Comment by gigago** [comment]
> I'll wait a bit more until I sent those two patches upstream, apparently there are a slew of Intel-designed laptops we didn't even know about, we need to make sure we add the quirks for all of them... Big companies...

Yeah, seems like a lot of noodling. Let's hope a more generic way of testing for quirks surfaces. By the way, there's also an LAPBC510 out, mainly differentiated by having an i5 processor. I'd bet two beers that it's BIOS exhibits the exact same quirks as the LAPBC710.

**Comment by plbossart** [comment]
> > I'll wait a bit more until I sent those two patches upstream, apparently there are a slew of Intel-designed laptops we didn't even know about, we need to make sure we add the quirks for all of them... Big companies...
> 
> Yeah, seems like a lot of noodling. Let's hope a more generic way of testing for quirks surfaces. By the way, there's also an LAPBC510 out, mainly differentiated by having an i5 processor. I'd bet two beers that it's BIOS exhibits the exact same quirks as the LAPBC710.

Yes, I am trying to get the list of all derivatives of the same design before sending this upstream

**Comment by plbossart** [comment]
> I'd bet two beers that it's BIOS exhibits the exact same quirks as the LAPBC710.

indeed, confirmed that the two skews are identical audio-wise. I updated the patches and will submit upstream next week.
