### ISSUE TITLE
HP Spectre 13-aw2020ca believes headphones are connected

### ISSUE THREAD

**Issue by willy613** [thesofproject/linux#3152]
hardware DMI string: HP Spectre x360 Convertible 13-aw2xxx
Kernel version: 5.14.0
SOF version 1.8

The speaker-test commands mentioned in issue 2700 work fine:

alsaucm -c sof-soundwire set _verb HiFi set _enadev Speaker
speaker-test -Dhw:0,2 -c2 -r48000

I get pink noise from left and right speakers as expected.  If I plug headphones in, I get audio out.  But unplugging the headphones, I get no sound from the speakers.  Running 'pavucontrol' shows the headphones as plugged in, when they are not.

Apologies if headphone presence detection is handled somewhere else in the stack ...

**Comment by plbossart** [comment]
If you using the -Dhw:x,y hardware devices, there is no automatic switch nor detection of headphone jacks.

a) -Dhw:0,0 is for headphone - even if not connected the output will consume data
b) -Dhw:0,2 is for speakers - it's completely independent from the headphone status.

the speakers and headphone are handled by two separate chips which can work independently, it's different to the traditional usages where you could have sound on either speaker or headphone.

**Comment by willy613** [comment]
Oh!  Thank you for explaining that.  I confirm that I can select speakers instead of headphones and everything works as expected.  I didn't even think to check whether I could switch manually.

**Comment by plbossart** [comment]
@willy613 sometimes it's a 'feature' that when removing headphones the sound is not automatically played on speakers - to avoid blasting the content which was assumed private. Android devices will e.g. pause music when removing headphones and ask the user to manually restart on speakers. Defining the 'right' behavior is tricky since someone will always be unhappy.

That said, if your sound server, PipeWire or PulseAudio is configured to automatically switch and it doesn't happen then it's a bug. I've seen similar cases in the past where device selection is not automatic, it was supposed to be fixed with recent PulseAudio/Gnome settings, but bugs might still be present.
