### ISSUE TITLE
Xiaomi Mi Notebook Pro 2020 - No speakers after suspend

### ISSUE THREAD

**Issue by itsByte** [thesofproject/linux#3333]
On my Mi Notebook Pro 2020 (i7 10510U, MX250, ALC256) the speakers work fine on startup, but when the laptop is woke up after sleep, they stop working, although the output is still marked as speakers, and the headphones port works fine. I already tried changing the snd_hda model to other ALC256 laptops, but it doesn't seem to fix it.

Until a previous version of the 5.14 kernel (or the alsa package), the workaround was to remove the intel hd audio pci device and force a rescan, this would (I think) trigger the amplifier initialize sequence and the speakers would work again, but since a later revision this workaround does not work anymore.

[alsa-info.txt](https://github.com/thesofproject/linux/files/7710839/alsa-info.txt)

I think this bug is related to the sof project, but I apologize if it is not.
Thanks in advance

**Comment by plbossart** [comment]
@itsByte the log shows you are not using the SOF driver, but the legacy snd-hda-intel driver.  The problem you are mentioning seems to be a codec driver issue.

I would recommend you file a bug at https://bugzilla.kernel.org/

Adding @kv2019i and @tiwai for feedback.

**Comment by itsByte** [comment]
Oh, sorry for the bad issue then. I just tried enabling the sof driver, but I get no audio, the speakers are not even detected.

**Comment by plbossart** [comment]
@itsByte no worries, it's confusing indeed.

Usually the problem is that the amplifiers are handled with dedicated 'verb' commands that are known to the Windows driver, but not documented and used for Linux.

You may want to look at the instructions provided here: https://github.com/ryanprescott/realtek-verb-tools/wiki/How-to-sniff-verbs-from-a-Windows-sound-driver

This was used in the past to solve amplifier configuration issues. It's not an easy task to deal with such a reverse-engineering task, but that's all I can suggest for now.

Alternatively maybe the Xiaomi support can point to a team or codec vendor that might have the information.

**Comment by itsByte** [comment]
Could it be possible that the verbs are correct on boot, but don't apply after resuming from suspend? Or maybe it is because the amplifier is automatically enabled on startup by the BIOS so Linux works "by luck". 
I will try to sniff the verbs when I have time to install Windows, thanks!

**Comment by itsByte** [comment]
Update: I have found the necessary verbs to enable the amplifier. Fortunately, only two are needed:
0x20 0x500 0x10
0x20 0x400 0x20
I will submit a bug report on the linux bugzilla, this thread can be closed if no further testing is required for this project
