### ISSUE TITLE
Discussion: ADL-P: Support in M/C driver for  RT711 headset codec for external Audio interface cards(AIOC) with different JD source

### ISSUE THREAD

**Issue by jairaj-arava** [thesofproject/linux#3668]
The soundwire RT711 headset codec  jack detection source is different on each version. For an instance, it is JD2_100k on on-board codec and it is JD2 on AIOC codecs. Listed below from the  RT711 codec driver jacke detection sources
https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/rt711.h#L242 
enum rt711_jd_src {
	RT711_JD_NULL,
	RT711_JD1,
	RT711_JD2,
	RT711_JD2_100K,
	RT711_JD2_1P8V_1PORT
};

We have the changes to support JD2_100k src in our M/C https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_sdw.c#L225 

	/* AlderLake devices */
	{
		.callback = sof_sdw_quirk_cb,
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "Intel Corporation"),
			DMI_MATCH(DMI_PRODUCT_NAME, "Alder Lake Client Platform"),
		},
		.driver_data = (void *)(RT711_JD2_100K |
					SOF_SDW_TGL_HDMI |
					SOF_BT_OFFLOAD_SSP(2) |
					SOF_SSP_BT_OFFLOAD_PRESENT),

However, to support the RT711 with JD2 src, is there any possibility that we can change the above driver data such that it supports both JD sources ?

**Comment by jairaj-arava** [comment]
@sathya-nujella @ranj063 @plbossart

**Comment by plbossart** [comment]
@jairaj-arava you already have a kernel parameter for snd_soc_sof_sdw, just take the default value for the quirk and set the bits you want. We can't have different settings in the driver for different hardware layouts, we have to assume the on-board codec is used. If you want to connect something else, you need to use quirks.

**Comment by rfeldman2534** [comment]
Summary of the problem we are trying to solve:

Linux Integration team is trying to enable Intel QA team to validate 'SNDW ADL-P RVP<->AIOC>GEN3.1' config (RT711_JD2),  using SOF daily kernel image. Note that this 'SNDW ADL-P RVP<->AIOC>GEN3.1'config uses sof-adl-rt711-l0-rt1316-l13-rt714-l2.tplg.
Also, we have to preserve SOF daily kernel support for 'SNDW ADL-P RVP' configs, which use onboard ALC711 (RT711_JD2_100K).

We have been able to enable correct AIOC.ALC711 headset (RT711_JD2) detection using a private SOF kernel build, which includes a simple sof_sdw_quirk_table[] patch (details below). However, this patch has not been accepted for upstreaming by the SOF team, because it would break 'SNDW ADL-P RVP' configs which use onboard ALC711 (RT711_JD2_100K), which are also supported.

Problem: 
We still don't have an SOF daily kernel which supports both 'SNDW ADL-P RVP<->AIOC>GEN3.1' (RT711_JD2) and 'SNDW ADL-P RVP' (RT711_JD2_100K) configs.

Therefore, Linux Integration team would like to request SOF team to enhance SOF kernel to support
both 'SNDW ADL-P RVP<->AIOC>GEN3.1' (RT711_JD2) and 'SNDW ADL-P RVP' (RT711_JD2_100K) configs. 


	Additional Details:

'SNDW ADL-P RVP<->AIOC>GEN3.1' config has been enabled using private SOF kernel build, using the following simple sof_sdw_quirk_table[] patch:

--- linux/sound/soc/intel/boards/sof_sdw.c.ORIG	2022-05-03 20:14:09.412179734 -0700
+++ linux/sound/soc/intel/boards/sof_sdw.c	2022-05-13 16:37:24.901725823 -0700
@@ -229,7 +229,7 @@
 			DMI_MATCH(DMI_SYS_VENDOR, "Intel Corporation"),
 			DMI_MATCH(DMI_PRODUCT_NAME, "Alder Lake Client Platform"),
 		},
-		.driver_data = (void *)(RT711_JD2_100K |
+		.driver_data = (void *)(RT711_JD2 |
 					SOF_SDW_TGL_HDMI |
 					SOF_BT_OFFLOAD_SSP(2) |
 					SOF_SSP_BT_OFFLOAD_PRESENT),

However, this patch has not been accepted for upstreaming by the SOF team, because it would break 'SNDW ADL-P RVP'  configs which use onboard ALC711 (RT711_JD2_100K), which are also supported...

Currently, SOF kernel relies on BIOS DMI info, to identify matching sof_sdw_quirk_table[] entries. 
This mechanism works fine to differentiate between different vendors and to set .driver_data accordingly,
but unfortunately BIOS DMI state does not provide enough information to differentiate between ADL-P.RVP which use onboard ACL711 vs. ADL-P.RVP<->AIOC.ALC711. For both of these configs, relevant DMI state is the same:

System Information
	Manufacturer: Intel Corporation
	Product Name: Alder Lake Client Platform
...
Base Board Information
	Manufacturer: Intel Corporation
	Product Name: AlderLake-P DDR5 RVP

Therefore, Linux Integration team would like to request SOF team to enhance SOF kernel to support
both 'SNDW ADL-P RVP<->AIOC>GEN3.1' (RT711_JD2) and 'SNDW ADL-P RVP' (RT711_JD2_100K) configs.

**Comment by plbossart** [comment]
@rfeldman2534 there's no magic here, if you have two hardware platforms identified with the *SAME* DMI quirk only one configuration will work out of the box, the other will require a kernel parameter set on the DUT.

**Comment by plbossart** [comment]
@rfeldman2534 to be clearer, we *CANNOT* detect what the JD values might be, it has to be set explicitly and provided to the machine driver. The DMI quirk is just a means to guess, but again if you have different settings for the same DMI quirk there's not much we can do for you.

**Comment by rfeldman2534** [comment]
Thanks for providing these clarifications.
We can add a manual step for QA to edit /etc/default/grub and add GRUB_CMDLINE_LINUX param like snd_intel_rt711_jd2=1. However, we will still need an SOF kernel patch to check for this kernel cmdline arg, and override corresponding .driver_data, set via sof_sdw_quirk_table[] DMI match.
Are you Ok with this approach?

**Comment by libinyang** [comment]
Based on this issue, I'm wondering whether there are productions using same DMI but have different HW JD configuration? If so, do we have rule to fix such confliction except the kernel parameter?

**Comment by plbossart** [comment]
@rfeldman2534 there is no development needed, you can already use the quirk parameter

````
modinfo snd-soc-sof-sdw
filename:       /lib/modules/5.18.0-rc2-test-05495-g870fe9a542bd-dirty/kernel/sound/soc/intel/boards/snd-soc-sof-sdw.ko
import_ns:      SND_SOC_INTEL_SOF_MAXIM_COMMON
import_ns:      SND_SOC_INTEL_HDA_DSP_COMMON
alias:          platform:sof_sdw
license:        GPL v2
author:         Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
author:         Rander Wang <rander.wang@linux.intel.com>
author:         Bard Liao <yung-chuan.liao@linux.intel.com>
description:    ASoC SoundWire Generic Machine driver
depends:        snd-soc-core,soundwire-bus,snd-soc-intel-hda-dsp-common,snd,snd-soc-intel-sof-maxim-common
retpoline:      Y
intree:         Y
name:           snd_soc_sof_sdw
vermagic:       5.18.0-rc2-test-05495-g870fe9a542bd-dirty SMP preempt mod_unload 
parm:           quirk:Board-specific quirk override (int) <<<<<< HERE!
````

**Comment by plbossart** [comment]
in other words, all you need is to set the quirk, either on the command line with snd-soc-sof-sdw.quirk=0xdeadbeef or 

options snd-sof-sof-sdw quick=0xdeadbeef added to a configuration file in /etc/modprobe.d/

**Comment by rfeldman2534** [comment]
Hello Pierre,

Thank you for providing this detailed information. I will validate that using this quirk parameter resolves rt711 jack detection issue on our SoundWire ADL-P RVP<->AIOC.Gen31 config, and provide an update.

Thanks,
Robert

**Comment by rfeldman2534** [comment]
Summary of my latest findings:

1. Verified that if “snd-soc-sof-sdw.quirk” parameter is not passed to unmodified SOF 5.17.0-rc1-daily kernel, global sof_sdw_quirk defaults to 0x50023 on Linux ADL-P.RVP<->AIOC.Gen31 config. This default initialization is handled by the following entry of the sof_sdw_quirk_table[], and sof_sdw_quirk bits 0-3 are used to encode JD_src:

{
                .callback = sof_sdw_quirk_cb,
                .matches = {
                        DMI_MATCH(DMI_SYS_VENDOR, "Intel Corporation"),
                        DMI_MATCH(DMI_PRODUCT_NAME, "Alder Lake Client Platform"),
                },
                .driver_data = (void *)(RT711_JD2_100K |
                                        SOF_SDW_TGL_HDMI |
                                        SOF_BT_OFFLOAD_SSP(2) |
                                        SOF_SSP_BT_OFFLOAD_PRESENT),
        },

2. Verified that passing “snd-soc-sof-sdw.quirk=0x50022” to SOF kernel (via GRUB_CMDLINE_LINUX),  on same config, results in JD_src getting set to RT711_JD2 (2), and also preserves the default state of all the sof_sdw_quirk bits in default quirk value. Corresponding snippet is dmesg, for this test: 

[    0.000000] Linux version 5.17.0-rc1-daily-default-20220401-g04fe31cf100d ([jenkins@sofbld03.ostc.intel.com](mailto:jenkins@sofbld03.ostc.intel.com)) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #dev SMP PREEMPT Fri Apr 1 14:21:16 PDT 2022
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.17.0-rc1-daily-default-20220401-g04fe31cf100d root=UUID=bdc392e6-e05c-4143-9ce3-e39bb52b3d18 ro console=tty1 console=ttyS0,115200 i915.modeset=1 i915.enable_dp_mst=1 i915.enable_psr=0 oops=panic panic=-1 splash quiet intel_pmc_core.warn_on_s0ix_failures=1 i915.enable_guc=2 snd_intel_dspcfg.dsp_driver=3 snd-soc-sof-sdw.quirk=0x50022 intel_iommu=on
…
[    9.185895] sof_sdw sof_sdw: Overriding quirk 0x50023 => 0x50022
[    9.185897] sof_sdw sof_sdw: quirk realtek,jack-detect-source 2
[    9.185898] sof_sdw sof_sdw: quirk SOF_SDW_TGL_HDMI enabled

Dmesg entries above are logged by sound/soc/intel/boards/sof_sdw.c::mc_probe():

static int mc_probe(struct platform_device *pdev)
{
              dev_dbg(&pdev->dev, "Entry %s\n", __func__);
              if (quirk_override != -1) {
                dev_info(&pdev->dev, "Overriding quirk 0x%lx => 0x%x\n",
                         sof_sdw_quirk, quirk_override);
                sof_sdw_quirk = quirk_override;
        }
        log_quirks(&pdev->dev);
              ...
}
static void log_quirks(struct device *dev)
{
        if (SOF_RT711_JDSRC(sof_sdw_quirk))
                dev_dbg(dev, "quirk realtek,jack-detect-source %ld\n",
                        SOF_RT711_JDSRC(sof_sdw_quirk));
...
}

Also, verified that AIOC.rt711 headset detection works as expected for this test, and that “Wrong JD source” is no longer present in dmesg.

Based on these results, I will update Linux SoundWire ADL-P BKM, which should enable QA to validate SoundWire functionality on Linux ADL-P<->AIOC.Gen31 configuration.

Thanks,
Robert

**Comment by rfeldman2534** [comment]
Hello Pierre,

When you get a chance, please take a look at the latest test results, described in my last update above, and confirm that we are on the same page for enabling rt711 jack detection on ADL-P<->AIOC config, by passing snd-soc-sof-sdw.quirk=0x50022” to SOF kernel (via GRUB_CMDLINE_LINUX). When this is confirmed, this issue can be closed.

Thanks,
Robert

**Comment by plbossart** [comment]
@rfeldman2534 if you are only changing the JD source from RT711_JD2_100K to RT711_JD2 then the following change looks good to me. The 4 lowest bits are allocated to JD sources, so you're changing from index 3 to index 2.

 0x50023 => 0x50022

**Comment by rfeldman2534** [comment]
Hello Pierre,

Thank you for your feedback.

Robert

**Comment by rfeldman2534** [comment]
Hello Jairaj,

Please confirm that you don't see any issues with the proposed /etc/default/grub change to enable rt711 jack_detection for the SNDW Linux ADL-P.RVP<->AIOC config, and then please close this issue.

Thanks,
Robert

**Comment by jairaj-arava** [comment]
@rfeldman2534 as discussed, let's go with the above command line override approach SNDW Linux ADL-P.RVP<->AIOC config. Hence, closing the issue.
