### ISSUE TITLE
restoring kcontrol values after resume

### ISSUE THREAD

**Issue by ranj063** [thesofproject/linux#389]
Just wondering when this should be done? 

Today it is done as soon as the system wakes up from runtime suspend or system suspend. runtime_suspend case is quite obvious that it needs to be right away. But is it critical to do this right after system resume? Or can this wait until after the pipeline is triggered? 

We're seeing suspend/resume failures while restoring kcontrols right after resuming. I wonder if this change would help.

**Comment by plbossart** [comment]
@ranj063 sorry I didn't see this earlier. two comments
1. the delay be implemented regardless when we enable IPCs when the pipelines is enabled (even outside of suspend/resume operations). That change depends on @mmaka1 changes for memory allocation.
2. playing with IPC timing is like shuffling the chairs on the Titanic deck. If the IPCs aren't reliable they will fail at some point, and to some extent it's better for debug to fail hard on resume rather than fail later when pipelines are enabled.

**Comment by ranj063** [comment]
@plbossart I think when we implement the smart suspend/smart resume feature this will be addressed automatically. So, I will close this one
