### ISSUE TITLE
Mic Mute LED broken by changes to use new LED handling layer

### ISSUE THREAD

**Issue by mrhpearson** [thesofproject/linux#4065]
Raised originally by Fedora community and tracked down to this commit:
https://github.com/thesofproject/linux/commit/9b014266ef8ad0159b39920a752f191bcd6f356c

This breaks the LED functionality on the X1 Carbon Gen 9. Still checking if other platforms are impacted by it but it looks like the P16 is impacted too. I haven't had a chance to check others but I suspect it will be a lot of platforms :( 

Please let me know what the next steps are to debug this and get it fixed.

Thanks!
Mark

**Comment by plbossart** [comment]
we need to ask @perexg

**Comment by perexg** [comment]
To make Mic LED work, you need to mute also the analog input (external jack) in the mixer by default. The SOF and HDA drivers register the Mic LED switch controls and the logic is to turn the LED on when both inputs are off.

The problem is that the SOF driver does not communicate with the HDA driver to avoid attaching the analog capture switch to the sound ctl-led (mic) for those platforms. But personally, I don't think that it's a wrong use case to turn LED only when all notebook inputs are off.

Also, you can remove the HDA control from the sound ctl-led using sysfs:

```
  echo "Capture Switch" > /sys/class/sound/ctl-led/mic/card0/detach
```

Note that you should identify the SOF/HDA card number at first (cat /proc/asound/cards).

Note2: The previous kernel behaviour (without the mentioned patch) was not correct either - both SOF / HDA drivers controlled the Mic LED independently, so the state sync was unpredictable (although users probably didn't notice it so much - retrigger).

**Comment by mrhpearson** [comment]
Closing this - issue was in alsa-ucm and was fixed by updates to ucm2/Intel/sof-hda-dsp
Thanks @perexg for your help resolving this.

**Comment by perexg** [comment]
Just a little note: The UCM fix https://github.com/alsa-project/alsa-ucm-conf/commit/79a8ec44d3dcf097f4a4492c506cbcf338324175 is just one way to "fix" the issue.

The list with control (mixer) switch elements which is tied to the LED control is configurable now. The manager which handles the mute keypress events may allow to select different behaviors (like mute all active inputs).
