### ISSUE TITLE
Upstream: PATCH 06/21 ASoC: SOF: Intel: Add Intel specific HDA DSP HW operations

### ISSUE THREAD

**Issue by ranj063** [thesofproject/linux#416]
> +	if (ret < 0) {
> +		dev_err(bus->dev, "error: cannot turn on display power on i915 after resume\n");
> +		return ret;
> +	}
> +
> +	/* init hda controller and power dsp up */
> +	return hda_resume(sdev);
> +}
> +
> +int hda_dsp_runtime_resume(struct snd_sof_dev *sdev)
> +{
> +	/* init hda controller and power dsp up */
> +	return hda_resume(sdev);
> +}

But why can't runtime PM turn on/off the display power?

**Comment by jocelyn-li** [comment]
@ranj063 any help needed?

**Comment by mengdonglin** [comment]
@ranj063 Do we still need this?

**Comment by ranj063** [comment]
@mengdonglin yes, this was a question from Takashi which we havent addressed. Can @libinyang take a look into this while he's making the other i915 related changes?

**Comment by libinyang** [comment]
@ranj063 @mengdonglin 
Which question are your talking about? I didn't find the email from Takashi for suspend/resume issue.

**Comment by libinyang** [comment]
BTW: I updated a patch https://github.com/thesofproject/linux/pull/569. It may be related to this topic.

**Comment by ranj063** [comment]
@libinyang the question is in the description. Basically, Takashi was asking why we power off/on i915 display only on system suspend/resume and not during runtime suspend/resume.

**Comment by libinyang** [comment]
@ranj063 
Actually, with Takashi's latest patch, we don't need handle i915 power any more. We can directly remove the i915 setting, please see my patch #569 
We need power on/off before in suspend/resume because hdmi codec will power on i915 when suspend and the hdmi codec didn't power off i915. So we need power off in controller suspend. As hdmi codec suspend/resume sequence has been changed, we don't need power off i915 power any more in controller suspend and the same in resume.

**Comment by plbossart** [comment]
closing, this doesn't seem to be applicable any longer
