### ISSUE TITLE
Playback and capture's volume kctls are mixed in one page

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/linux#43]
There're different views of kctl in amixer setting, but we found that all kctls of playback and capture are mixed together. For example, in playback view page, we also can found the kctl of capture and vice versa. This is a common issue on each platform.
![image](https://user-images.githubusercontent.com/29194447/42990571-93c9f556-8c35-11e8-8ce7-8be813ab07e0.png)

This bug is moved from https://github.com/thesofproject/sof/issues/50 to here.

**Comment by ZhendanYang** [comment]
This issue still exists with latest code base.
sof-dev : 7889a7ade4e20a81e297e3f5a5aea3b5d7fa55ef

**Comment by bardliao** [comment]
I think the control name should be end with 'Playback Volume' or 'Capture Volume'.  ie. It should not be end with PIPELINE_ID.  For example, 'PGA1.0 Master Playback Volume 1' is not a good naming style. We can reorder it to 'PGA1.0 1 Master Playback Volume' or just remove the PIPELINE_ID from the control name if it is not necessary.

**Comment by plbossart** [comment]
@ranj063 can you comment on what the names mean? What does PGAX.Y mean? I agree with Bard that there is an assumption the Playback Volume or Capture Volume are last.

**Comment by zhuyingjiang** [comment]
Add track info:
This issue is moved from SOF issue [#50](https://github.com/thesofproject/sof/issues/50),
after analysis, it ends up with the SOF topology name format, so fix will be at the SOF side.
The first SOFT PR [#139](https://github.com/thesofproject/soft/pull/139) moved to SOF [#654](https://github.com/thesofproject/sof/pull/654) since the SOFT depo moved into SOF.
The [#654](https://github.com/thesofproject/sof/pull/654) including the fix of this issue and barged in by an enhancement. Will reopen [#654](https://github.com/thesofproject/sof/pull/654) and separate the fix.

**Comment by zhuyingjiang** [comment]
Close as fixed by [#654](https://github.com/thesofproject/sof/pull/654)

**Comment by xiulipan** [comment]
@zhuyingjiang I think you mean https://github.com/thesofproject/sof/pull/654

**Comment by zhuyingjiang** [comment]
@xiulipan Thanks! updated.
