### ISSUE TITLE
No Sound from headphone jack, headphone mic input works (Arch, WM510205, Lenovo Yoga-2-851F)

### ISSUE THREAD

**Issue by scragnoth** [thesofproject/linux#4491]
My original issue is #4420 

After I got help on my original matter (had no sound at all, due to missing necessary kernel modules in arch which didn't load by default)  by @jwrdegoede I realized shortly after that I cannot use the headphone jack. It won't detect any headphones I plug in. The only jack-related function which works is the mic functionality, so if I plug a 4-pole-headset in, I can use the mic which is built into the headset. Pipewire switches automatically to the headset microphone if it is present.

Headphones show up in the volume control as an option, but they're always "unplugged", regardless if present or not. I can hear only some static through the headphones.

What I tried / found out: I tried HDA Jack Retask, but that doesn't work with SOF-Firmware / is not meant for it. I switched from pulseaudio to pipewire. I blacklisted snd_hdmi_lpe_audio since I read that it might cause conflicts.

I suspect a wrong setting in alsamixer. Since the mic component of the jack detection works, the rest should work, too.

Unfortunately, the `amixer -c#` command returns a whopping 2090 lines. I put it into pastebin ...

https://pastebin.com/dvHLKnps

I realized pretty quick that "Speaker Digital" (line 9) is the internal speaker of the tablet. I think the headphone jack could be "HPOUT1 Digital" (line 616) or "HPOUT2 Digital" (line 737). "HPOUT2 Digital" is currently on, "HPOUT1 Digital" is off. I tried it the other way around but no dice. I also don't know if switching too many things on at the same time results in conflicts of some kind.
There are so many items where I can choose one of several options. "AIF1TX1 Input 1" (line 108), for example. If I google that, I can't find anything conclusive.

It's so unfortunate that @jwrdegoede (somehow his name isn't auto-recognized here anymore) didn't answer anymore after helping me so much in the start, I even send him an e-mail about two weeks ago. He wrote that he has this exact tablet, working.
I mentioned that I couldn't get sound from the headphone jack in the original issue mentioned in the beginning, but no one answered there.

I tried bluetooth as a workaround, I can connect (not to all bluetooth headphones tho, one I'd like to use refuses to pair, it works on my phone flawlessly) but the sound skips sometimes and it eats into the performance unfortunately, making before playable games unplayable (that's my goal with this tablet, to play some games while on the train). I observed the weaker performanceit already when I used a bluetooth- instead of a wired gamepad.

**Comment by jwrdegoede** [comment]
Sorry for being very slow with replying to this (I've been buried in other work).

So I have dug my own Lenovo Yoga-2-851F out of storage and ran the following tests:

1. Test with the installed Fedora 36 with kernel 6.3.0-rc7: speakers + headphones + builtin mic + headset mic all work.
2. Test with the installed Fedora 36 with kernel 6.6.0-rc1: everything still works
3. Test with Fedora 38 x86_64 workstation livecd: hmm, that does not work at all (no speaker output), since there is no speaker output this likely is a different issue. I'll investigate this separately.

I suspect that the your problem is the same problem as which I had when I originally added support for the WM5102 codec on these tablets, back then I also could not get the headphones out to work and it took me a long long time to find the culprit.

The problem is the debug setting in the BIOS, which changes the left/right pins of the headphone jack to debug pins. To check this do the following:

1. Press volume up and then while holding volume up pressed power on the tablet, this will get you into the BIOS.
2. Navigate to "Bios Settings"
3. Select "Configuration"
4. Change "USB Debug Support" to "Off"
5. Select "Exit" and then "Exit Saving Changes"

**Comment by jwrdegoede** [comment]
Ok, so the problem with the F38 livecd is that its kernel is missing this fix:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c963e2ec095cb3f855890be53f56f5a6c6fbe371

Which is present in kernels >= 6.2.16 or >= 6.3.3 or >= 6.4.0

Note this causes the sound to not work at all, rather then just the headphones out to not work. I still think the BIOS "USB Debug Support" option is the most likely cause of this issue.

**Comment by jwrdegoede** [comment]
Ok, I just finished a clean F38 install on my Lenovo Yoga-2-851F, updated the kernel because of the mentioned kernel bug and after that everything works fine.

Then I also installed all other F38 updates to rule out recent alsa-ucm or pipewire changes and everything still works fine.

So this either is the mentioned BIOS setting issue, or something specific to Arch Linux.

**Comment by scragnoth** [comment]
Thank you again @jwrdegoede 

> The problem is the debug setting in the BIOS, which changes the left/right pins of the headphone jack to debug pins. To check this do the following:
> 
>     1. Press volume up and then while holding volume up pressed power on the tablet, this will get you into the BIOS.
> 
>     2. Navigate to "Bios Settings"
> 
>     3. Select "Configuration"
> 
>     4. Change "USB Debug Support" to "Off"
> 
>     5. Select "Exit" and then "Exit Saving Changes"

That did the trick, the option was enabled on my tablet. After I disabled it and logged into Arch, headphones were detected right away and the sound that comes out of them is normal (no more static noise).
