### ISSUE TITLE
Up2: enable 3 displays with HDMI and DP1.2 MST playback in parallel

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#504]
Filing as an enhancement to make sure this test is added to our validation.
The Up2 board has 2 connectors: 1 HDMI and 1 DP1.2 (which means DP MST is possible). That means in theory we can enable playback on the 3 streams supported by the iDISP codec and hear independent audio on 3 monitors.

**Comment by mengdonglin** [comment]
Close this feature since Keqiao has verified on both GLK and WHL:
Verified the DP-MST on GLK and WHL RVP, audio works well on each monitor and the sound is clean without noise, but it can only support 2 DP monitors at most through the MST hub. The third one is not supported(black screen) due to lack of GFX support.

**Comment by mengdonglin** [comment]
@stevyan Please add DP-MST on UP2 in our daily test when the DP-MST hub arrives in your lab.

**Comment by plbossart** [comment]
On 4/8/19 8:52 AM, Mengdong Lin wrote:
> @stevyan <https://github.com/stevyan> Please add DP-MST on UP2 in our 
> daily test when the DP-MST hub arrives in your lab.

And share the config used please.
