### ISSUE TITLE
Update the IPC re-try mechanism

### ISSUE THREAD

**Issue by ranj063** [thesofproject/linux#551]
We dont have a mechanism to rey-try failed IPC's at the moment

**Comment by wenqingfu** [comment]
should we re-try failed IPC automatically, or let the tx message caller decide?

**Comment by lyakh** [comment]
If we decide to re-try failing IPCs automatically, that would mean that all of them would be retried. Are there any cases when we rather don't want to retry? E.g. sometimes we can realise, that this is a hard failure and re-trying won't fix it anyway. In some other cases some specific failing IPCs could be "normal" and should be ignored instead of being re-tried? Can the core differentiate between such cases automatically, based on error codes or some flags, or should the caller decide?

**Comment by plbossart** [comment]
good question @lyakh 
We should probably bin the 'failing IPCs' in two categories
- explicit NAK. Here it's a configuration issue and the firmware will not respond differently if we retry (The definition of insanity is doing the same thing over and over again and expecting a different result)
- timeout. That's the only case where I could see the use of retries being useful, just to get beyond a temporary delay in handling a command.

**Comment by plbossart** [comment]
@ranj063 I am leaning on closing this request, there's no real motivation for retrying IPCs, is there?

**Comment by lgirdwood** [comment]
@plbossart only motivation to retry is for any IPC that returns -EBUSY or -EAGAIN

**Comment by plbossart** [comment]
> @plbossart only motivation to retry is for any IPC that returns -EBUSY or -EAGAIN

and do we have any? if yes, we have a real gap in our solution then.

**Comment by lgirdwood** [comment]
I dont think we have any EAGAIN or EBUSY today, but that's not to say they cant be added.

**Comment by plbossart** [comment]
I'd rather focus on recovery in case of timeouts, which are currently fatal and require a reboot.
We'll deal with retries for -EGAIN/-EBUSY when we have a need for them, likely a 2021 discussion already....

**Comment by plbossart** [comment]
@lgirdwood @ranj063 I don't think we have any plans for a re-try when an IPC fails. Shall we close this one?

**Comment by plbossart** [comment]
I don't see a path or need for this, closing.
