### ISSUE TITLE
No exception data / etrace  in fs after panic.

### ISSUE THREAD

**Issue by dabekjakub** [thesofproject/linux#602]
After  DSP Panic there is no data in exception or etrace fs.

Similar to #296 however it is new.

[log_trace_dmsg.txt](https://github.com/thesofproject/linux/files/2803259/log_trace_dmsg.txt)

kernel: sof-kernel/topic/cros-sof-v4.14-rebase  a83979d6b03f0184e50138991b595643b239fdd0
FW: 297958f418081e155d8264af1fdc98058ed90746 (UP arch)

Easy reproduction for panic on above config after about 20 iterations of :

aplay -Dhw:0,1 test.wav & aplay -Dhw:0,0 test.wav & aplay -Dhw:0,6 test.wav 

Blocks:
https://github.com/thesofproject/sof/issues/901

**Comment by ranj063** [comment]
@dabekjakub is there an easier way to reproduce a DSP panic?

**Comment by wenqingfu** [comment]
Can you please add comment why you close this issue?  looks like you were asking for something then it's closed. Accidentally clicked the wrong button?

**Comment by ranj063** [comment]
@wenqingfu sorry about that, an accident!

**Comment by dabekjakub** [comment]
We can always prepare fw which is just dividing by zero in any moment You want or just put panic call in anywhere. Effect should be the same.

**Comment by ranj063** [comment]
@dabekjakub i added a divide by zero in th volume component set cmd call but all I got was a IPC time out. Do you mind sending me a patch that will generate an exception?

**Comment by dabekjakub** [comment]
https://github.com/dabekjakub/sof/tree/fake_exception

It should exception just after kernel load. If for any reason You do not start any stream at startup just send stream start command and it should do it.

**Comment by ranj063** [comment]
@dabekjakub Thanks! let me give this a try today

**Comment by ranj063** [comment]
@dabekjakub with your fw change: I see the following. Doesnt look like it is an exception though

[  104.248138] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[  104.248147] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[  104.248154] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[  104.248159] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[  104.248171] sof-audio-pci 0000:00:0e.0: rate_min: 48000 rate_max: 48000
[  104.248176] sof-audio-pci 0000:00:0e.0: channels_min: 2 channels_max: 2
[  104.248185] sof-audio-pci 0000:00:0e.0: pcm: hw params stream 0 dir 0
[  104.248194] sof-audio-pci 0000:00:0e.0: generating page table for 0000000022cfb084 size 0xff00 pages 16
[  104.248222] sof-audio-pci 0000:00:0e.0: period_bytes:0x480
[  104.248226] sof-audio-pci 0000:00:0e.0: periods:56
[  104.248242] sof-audio-pci 0000:00:0e.0: stream_tag 1
[  104.550268] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x60010000 size 0x6c
[  104.550290] sof-audio-pci 0000:00:0e.0: status: fw entered - code 00000005
[  104.550438] sof-audio-pci 0000:00:0e.0: error: unexpected fault 0x00000000 trace 0x00004000
[  104.550445] sof-audio-pci 0000:00:0e.0: error: waking up any trace sleepers
[  104.550471] sof-audio-pci 0000:00:0e.0: error: hw params ipc failed for stream 1
[  104.550481] sof-audio-pci 0000:00:0e.0: ASoC: 0000:00:0e.0 hw params failed: -110
[  104.550491]  Port5: ASoC: hw_params FE failed -110
[  104.551729] sof-audio-pci 0000:00:0e.0: pcm: free stream 0 dir 0
[  104.854215] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x60030000 size 0xc
[  104.854238] sof-audio-pci 0000:00:0e.0: status: fw entered - code 00000005
[  104.854386] sof-audio-pci 0000:00:0e.0: error: unexpected fault 0x00000000 trace 0x00004000
[  104.854393] sof-audio-pci 0000:00:0e.0: error: waking up any trace sleepers

**Comment by dabekjakub** [comment]
I am 100% positive this FW triggers exception after any stream trigger is sent to fw. I saw panic info in my tests on chrome platform(there was info passed in dmesg). Above looks like FW is dead but as if kernel did not acknowledge that FW crashed.

**Comment by ranj063** [comment]
@dabekjakub I have tried this divide by 0 trick about a year ago and it definitely triggered an exception and the kernel acknowledged it too. Not sure what changed along the way.

**Comment by dabekjakub** [comment]
I am sure that this exception is passed since i can see exception data in dmesg on my kernel build (commit stated in initial comment) but not in exception fs. Maybe You have latest kernel code and it has more than one issue.

**Comment by ranj063** [comment]
@dabekjakub i managed to create an exception by removing the volume cmd callback from the code and I am able to see the exception data when I do a hexdump /sys/kernel/debug/sof/exception as below:
0000000 0058 0000 000c 0000 0000 0000 0020 0006
0000010 0000 0000 756c be02 48b0 be02 0000 0000
0000020 0000 0000 0000 0000 0000 0000 0720 0006
0000030 0722 0006 0000 0000 0000 0000 0000 0000
0000040 0000 0000 0000 0000 01d0 0001 0222 0000
0000050 001d 0000 fcf0 be07 0000 0000 0000 0000
0000060 0000 0000 0000 0000 0000 0000 0000 0000
*
0000080 0000 0000 1468 be05 0000 0000 79bd 007f
0000090 0000 0000 0004 0000 0000 0000 0400 0000
00000a0 0045 0000 0000 0000 0f30 0006 001d 0000
00000b0 0824 2001 8a00 be06 0064 0000 1500 be05
00000c0 0180 0000 000c 0000 16d3 be02 fb88 be01
00000d0 fba6 be01 0000 0000 0000 0000 0001 0000
00000e0 0824 2001 ffff 00ff 7361 007f 0000 0000
00000f0 f99c 2000 0001 0000 0000 0000 005c 0000
0000100 6658 2000 102c 9e05 0000 0000 0000 0000
0000110 1458 be05 1e26 be02 fdf0 be07 1400 be05
0000120 4940 9e06 8800 be06 807c be04 0018 0000
0000130 8d00 be06 006c 0000 0000 5001 0000 0000
0000140 0001 0000 0000 0000 0000 0000 0000 0000
0000150 0000 0000 0000 0000 0000 0000 0000 0000
0000160 0000 0000 0000 0000 0000 0000 0002 0000
0000170 0000 0000 0000 0000 0000 0000 0000 0000
*
0000190 0016 0000 4ed0 be02 fe50 be07 1180 be05
00001a0 1180 be05 c89c be01 fe60 be07 0000 0000
00001b0 0064 0000 2602 be02 fe70 be07 1458 be05
00001c0 8060 be04 25e6 be02 fe80 be07 1400 be05
00001d0 3c00 be05 0000 0000 0000 0000 0064 0000
00001e0 0000 0000 0599 be01 feb0 be07 1400 be05
00001f0 0000 0000 aaca be01 feb0 be07 0080 0000
0000200 0003 0000 0000 0000 0000 0000 0000 0000
0000210 0002 0000 7ac2 fe02 fed0 be07 11c0 be05
0000220 147c be05 5780 be04 25d4 be02 11c4 be05
0000230 11c4 be05 756c 7e02 ff00 be07 fff7 ffff
0000240 0000 0000 11c4 be05 0008 0000 0000 0000
0000250 076c 2001 0020 0006 11c4 be05 0001 0000
0000260 1458 be05 7578 be02 ff60 be07 8400 17d7
0000270 756c fe02 756c be02 0730 0006 0018 0000
0000280 ffff ffff 0000 0000 0000 0000 1184 be05
0000290 0520 0006 8088 be04 3f8e be02 3ef8 be02
00002a0 3f06 be02 7556 be02 ff40 be07 0000 0000
00002b0 8064 be04 1140 be05 8400 17d7 0e00 0000
00002c0 8400 17d7 7600 be02 ff80 be07 0000 0000
00002d0 5040 be04 ffff ffff 000d 0000 0010 0505
00002e0 4e2c be04 fa93 be01 ffa0 be07 8048 be04
00002f0 0001 0000 0008 0000 3200 0000 4180 0000
0000300 0080 0000 fb18 be01 ffc0 be07 8048 be04
0000310 de00 be00 0008 0000 3600 0000 4000 0000
0000320 0000 0000 0b5e 7e01 ffe0 be07 0001 0000
0000330 2d80 be04 0008 0000 0000 0000 0000 0000
0000340 0000 0000 0000 0000 0000 be08 0000 0100
0000350 0020 0004 2d84 be04 ffff ffff 0000 0000
0000360 0000 0000 0000 0000 0000 0000 0000 0000
*
0000800


Could you please try disabling runtime pm so you dont lose mem window context due to the DSP entering D3?
echo on > /sys/devices/pci0000\:00/0000\:00\:0e.0/power/control

We recently made several changes to the debugfs in the driver. So you need the latest code for sure.

**Comment by dabekjakub** [comment]
Confirmed , works on latest kernel - closing.
