### ISSUE TITLE
Add LBM quirk in the header

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/linux#621]
According to discussion in PR #937 in sof repo I rise a need to add LPM quirk in the header.

**Comment by plbossart** [comment]
@emilchudzik you want a quirk in which header?

If you are talking about adding a quirk in dai-intel.h, then it's not really compatible with the approach of adding a kcontrol or using debugfs, it'd be a topology-defined setting. In other words it'd be a fixed setting once the topology file is loaded.

**Comment by emilchudzik** [comment]
@plbossart I just raise this issue for suggestions from Liam from https://github.com/thesofproject/sof/pull/937.

**Comment by plbossart** [comment]
On 2/4/19 8:09 AM, Emil_Chudzik wrote:
>
> @plbossart <https://github.com/plbossart> I just raise this issue for 
> suggestions from Liam from #937.
>
>
Understand but we are not aligned on the directions

If you want to use the existing SSP quirks, then it's a topology fix and 
it's pretty easy to enable

If you want to use the .set_loopback_mode callback then we need a new 
IPC. I would err on the side of removing this callback since it's not 
mapped to any existing IPCs and it only makes sense for some DAIs.

@lgirdwood, thoughts?

**Comment by plbossart** [comment]
LBM added to kernel headers, but support for quirks is missing in the first place. Added issue https://github.com/thesofproject/linux/issues/640 to track this missing functionality
