### ISSUE TITLE
ABI/topology: fail at pipeline level instead of at elementary component level

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#844]
Since we allow MINOR ABI changes to add new components (DAI types/processing elements), the topology parsing need to ignore unknown DAIs, components or tuples. 

It will not instantiate pipelines which contain unsupported elements (no IPC required) and will delete any pipeline that fails to be instantiated by the FW during the PIPELINE_COMPLETE IPC. i.e. pipeline is deleted in FW and in driver DAPM.

Filing as P2 since it's a pretty major surgery of the topology that's required, this is not a typical 'enhancement'

**Comment by plbossart** [comment]
I don't even remember what I was asking for, closing.

**Comment by paulstelian97** [comment]
I'm thinking of a related issue: If at NXP we make a board with a mixer and two normal pipelines going into that pixel, one basic ALSA and one using compress, and the compress one fails due to missing firmware support, it would be nice if the basic ALSA one survives and is usable. This sounds like a more general variant of that. If you want, I can post a new issue discussing this specific use case.
